name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: git@e.coding.net:starblazer/projectb/wxdl-app.git
        platform: coding
        ssh-key: ${{ secrets.sshkey }}
      
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
